#!/usr/bin/env python3
"""Generate self-contained IP introduction.html from IPGen / packager artifacts."""

from __future__ import annotations

import argparse
import html
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

DEFAULT_MAIN_DOCS_URL = "https://tinyclunx33.tinyvision.ai"

# Register HTML / header artifacts generated by IPGen but omitted from packaged IP docs.
EXCLUDED_REGISTER_STEMS = frozenset({"debug_regs", "usb_manager"})
EXCLUDED_HEADER_NAMES = frozenset(
    {f"{stem}_def.h" for stem in EXCLUDED_REGISTER_STEMS}
)

PORT_RE = re.compile(
    r"(?P<dir>input|output|inout)\s+"
    r"(?:(?:wire|reg|logic)\s+)?"
    r"(?:(?:\[(?P<msb>\d+):(?P<lsb>\d+)\]\s+)?)?"
    r"(?P<name>\w+)",
    re.IGNORECASE,
)

# Indexed stream handshake: <prefix>_<n>_<signal>
STREAM_PORT_RE = re.compile(r"^(?P<prefix>.+?)_(?P<idx>\d+)_(?P<suffix>\w+)$")
STREAM_SUFFIXES = frozenset({"valid", "ready", "last", "data", "payload_fragment", "payload_last"})

CLK_PORT_RE = re.compile(r"^clk(?P<freq>\d+)MHz_(?P<kind>clk|resetn)$", re.IGNORECASE)
WB_PORT_RE = re.compile(r"^wb_(?P<dir>m2s|s2m)_(?P<bus>[\w]+)_(?P<signal>\w+)$", re.IGNORECASE)
WB_LEGACY_RE = re.compile(r"^wb(?:Ext|_ext_bus)_(?P<signal>\w+)$", re.IGNORECASE)
PMB_PORT_RE = re.compile(
    r"^pmb_(?P<bus>[\w]+)_(?P<channel>cmd|rsp)_(?P<signal>\w+)$",
    re.IGNORECASE,
)
PMB_LEGACY_RE = re.compile(
    r"^pmbExt_(?P<channel>cmd|rsp)_(?:(?:payload)_)?(?P<signal>\w+)$",
    re.IGNORECASE,
)

WB_SIGNAL_LABELS = {
    "cyc": "cycle",
    "stb": "strobe",
    "we": "write enable",
    "adr": "address",
    "dat": "data",
    "ack": "acknowledge",
    "err": "bus error",
    "sel": "byte select",
    "cti": "cycle type",
    "bte": "burst type",
    "dat_mosi": "write data",
    "dat_miso": "read data",
}

STREAM_SUFFIX_LABELS = {
    "valid": "data valid",
    "ready": "ready (back-pressure)",
    "last": "packet last beat",
    "data": "data beat",
    "payload_fragment": "data beat",
    "payload_last": "packet last beat",
}

PMB_SIGNAL_LABELS = {
    "valid": "transfer valid",
    "ready": "transfer ready (back-pressure)",
    "write": "write (1) or read (0)",
    "address": "byte address",
    "data": "read/write data",
    "mask": "byte lane mask (writes)",
}

PROCESSOR_CLOCK_DOMAIN = "processor clock domain (typically 60–75 MHz)"

# Per-port descriptions only where they add information beyond the port name.
CATEGORIES_WITH_PORT_DESCRIPTIONS = frozenset({"clocks", "streams", "wishbone", "pmb", "interrupts"})

# Category key -> (display title, sort rank). Lower rank appears first.
CATEGORY_META: dict[str, tuple[str, int]] = {
    "clocks": ("Clock & Reset", 10),
    "streams": ("Data Streams", 20),
    "interrupts": ("Interrupts", 30),
    "usb": ("USB PHY", 40),
    "wishbone": ("Wishbone", 50),
    "pmb": ("Pipelined Memory Bus", 52),
    "aps_sram": ("APS SRAM", 55),
    "spiflash": ("SPI Flash", 60),
    "uart": ("UART", 70),
    "i2c": ("I2C", 80),
    "jtag": ("JTAG", 90),
    "gpio": ("GPIO & Status", 100),
    "other": ("Other", 1000),
}


@dataclass(frozen=True)
class PortInfo:
    name: str
    direction: str
    width: str
    category: str
    description: str


def extract_module_ports(text: str) -> list[tuple[str, str, str]]:
    match = re.search(r"module\s+\w+\s*\((.*?)\)\s*;", text, re.DOTALL | re.MULTILINE)
    if not match:
        return []

    ports: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    for port in PORT_RE.finditer(match.group(1)):
        name = port.group("name")
        if name in seen:
            continue
        seen.add(name)
        direction = port.group("dir").lower()
        if port.group("msb") is not None:
            msb = int(port.group("msb"))
            lsb = int(port.group("lsb"))
            width = f"[{max(msb, lsb)}:{min(msb, lsb)}]"
        else:
            width = ""
        ports.append((name, direction, width))
    return ports


def is_stream_port(name: str) -> bool:
    match = STREAM_PORT_RE.match(name)
    return match is not None and match.group("suffix") in STREAM_SUFFIXES


def stream_groups(port_names: set[str]) -> dict[str, list[int]]:
    groups: dict[str, set[int]] = defaultdict(set)
    for name in port_names:
        match = STREAM_PORT_RE.match(name)
        if match and match.group("suffix") in STREAM_SUFFIXES:
            groups[match.group("prefix")].add(int(match.group("idx")))
    return {prefix: sorted(indices) for prefix, indices in sorted(groups.items())}


def clock_domains(port_names: set[str]) -> list[tuple[int, str]]:
    domains: dict[int, str] = {}
    for name in port_names:
        match = CLK_PORT_RE.match(name)
        if match and match.group("kind").lower() == "clk":
            freq = int(match.group("freq"))
            domains[freq] = f"clk{freq}MHz"
    return sorted((freq, label) for freq, label in domains.items())


def primary_clock_label(port_names: set[str]) -> str:
    domains = clock_domains(port_names)
    if not domains:
        return "the system clock"
    # Prefer the fastest declared clock as the default reference in prose.
    return domains[-1][1]


def is_pmb_port(name: str) -> bool:
    return PMB_PORT_RE.match(name) is not None or PMB_LEGACY_RE.match(name) is not None


def categorize_port(name: str) -> str:
    if CLK_PORT_RE.match(name):
        return "clocks"
    if is_stream_port(name):
        return "streams"
    if name.endswith("_irq"):
        return "interrupts"
    lower = name.lower()
    if lower.startswith("usb") and "_" in name:
        return "usb"
    if WB_PORT_RE.match(name) or WB_LEGACY_RE.match(name):
        return "wishbone"
    if is_pmb_port(name):
        return "pmb"
    if lower.startswith("phy_"):
        return "aps_sram"
    if name.startswith("spiflash_"):
        return "spiflash"
    if name.startswith("uart_"):
        return "uart"
    if name in ("scl", "sda") or name.startswith("i2c"):
        return "i2c"
    if name.startswith("jtag_"):
        return "jtag"
    if name.endswith("_led") or name.endswith("_led0"):
        return "gpio"
    return "other"


def humanize_identifier(text: str) -> str:
    return re.sub(r"\s+", " ", text.replace("_", " ")).strip()


def describe_clock_port(name: str) -> str | None:
    match = CLK_PORT_RE.match(name)
    if not match:
        return None
    freq = match.group("freq")
    if match.group("kind").lower() == "clk":
        return f"{freq} MHz clock"
    return f"Active-low reset for the {freq} MHz domain"


def describe_stream_port(name: str) -> str | None:
    match = STREAM_PORT_RE.match(name)
    if not match or match.group("suffix") not in STREAM_SUFFIXES:
        return None
    suffix = match.group("suffix")
    label = STREAM_SUFFIX_LABELS.get(suffix, humanize_identifier(suffix))
    return label


def describe_wishbone_port(name: str) -> str | None:
    match = WB_PORT_RE.match(name)
    if match:
        role = "master" if match.group("dir").lower() == "m2s" else "slave"
        signal = match.group("signal").lower()
        label = WB_SIGNAL_LABELS.get(signal, humanize_identifier(signal))
        return f"Wishbone {label} ({role})"

    legacy = WB_LEGACY_RE.match(name)
    if legacy:
        signal = legacy.group("signal").lower()
        role = "master" if signal in {"cyc", "stb", "we", "adr", "dat_mosi"} else "slave"
        label = WB_SIGNAL_LABELS.get(signal, humanize_identifier(signal))
        return f"Wishbone {label} ({role})"

    return None


def describe_pmb_port(name: str) -> str | None:
    match = PMB_PORT_RE.match(name) or PMB_LEGACY_RE.match(name)
    if not match:
        return None
    channel = match.group("channel").lower()
    signal = match.group("signal").lower()
    if signal == "data" and channel == "rsp":
        label = "read data"
    elif signal == "data" and channel == "cmd":
        label = "write data"
    else:
        label = PMB_SIGNAL_LABELS.get(signal, humanize_identifier(signal))
    channel_label = "command" if channel == "cmd" else "response"
    return f"PMB {channel_label} {label}"


def describe_irq_port(name: str, width: str) -> str | None:
    if not name.endswith("_irq") or not width:
        return None
    return (
        f"Interrupt vector {name} {width}; bit i maps to CPU interrupt index "
        f"(base + i, see device tree overlay)"
    )


def describe_port(name: str, direction: str, *, clock_label: str, width: str = "") -> str:
    category = categorize_port(name)
    if category not in CATEGORIES_WITH_PORT_DESCRIPTIONS:
        return ""

    for describer in (
        lambda: describe_clock_port(name),
        lambda: describe_stream_port(name),
        lambda: describe_wishbone_port(name),
        lambda: describe_pmb_port(name),
        lambda: describe_irq_port(name, width),
    ):
        text = describer()
        if text:
            return text
    return ""


def enrich_ports(ports: list[tuple[str, str, str]]) -> list[PortInfo]:
    port_names = {name for name, _, _ in ports}
    clock_label = primary_clock_label(port_names)
    return [
        PortInfo(
            name=name,
            direction=direction,
            width=width,
            category=categorize_port(name),
            description=describe_port(name, direction, clock_label=clock_label, width=width),
        )
        for name, direction, width in ports
    ]


def category_title(key: str) -> str:
    meta = CATEGORY_META.get(key)
    return meta[0] if meta else humanize_identifier(key).title()


def category_sort_key(key: str) -> int:
    return CATEGORY_META.get(key, (key, 999))[1]


def section_intro(category: str, ports: list[PortInfo], port_names: set[str]) -> str:
    clock_label = primary_clock_label(port_names)
    domains = clock_domains(port_names)

    if category == "clocks":
        if domains:
            listed = ", ".join(label for _, label in domains)
            return f"Clock and reset ports for the declared domains: {listed}."
        return "Clock and reset ports."

    if category == "streams":
        groups = stream_groups(port_names)
        stream_count = sum(len(indices) for indices in groups.values())
        if stream_count == 0:
            return (
                "Packetized stream interfaces toward the host stack "
                f"in the {PROCESSOR_CLOCK_DOMAIN}."
            )
        stream_word = "stream" if stream_count == 1 else "streams"
        return (
            f"{stream_count} independent host-bound {stream_word} using valid/ready handshaking "
            f"with data and last-beat signaling, clocked in the {PROCESSOR_CLOCK_DOMAIN}."
        )

    if category == "interrupts":
        return (
            "External interrupt inputs into the SoC interrupt controller. "
            "Index assignment is described in the device tree overlay when present."
        )

    if category == "usb":
        return (
            "USB PHY-facing ports routed through the IP top level. "
            "Connect to the board transceiver, reference clock, and connector."
        )

    if category == "wishbone":
        has_master = any(p.name.startswith("wb_m2s_") for p in ports)
        has_slave = any(p.name.startswith("wb_s2m_") for p in ports)
        if has_master and has_slave:
            role = "Wishbone master and slave interfaces"
        elif has_master:
            role = "Wishbone master interface (core initiates bus cycles)"
        elif has_slave:
            role = "Wishbone slave interface (external master accesses the core)"
        else:
            role = "Wishbone bus interface"
        return f"{role} for memory-mapped access to external logic."

    if category == "pmb":
        return (
            "Pipelined Memory Bus slave interface for memory-mapped access from external logic. "
            "The command channel uses valid/ready handshaking; read data is returned on the "
            "response channel."
        )

    if category == "aps_sram":
        return (
            "PHY-facing ports for the external APS SRAM device "
            "(clock, chip enable, data, and data/strobe mux)."
        )

    if category == "spiflash":
        return "SPI flash interface to external boot/storage device."
    if category == "uart":
        return "UART serial console / debug port."
    if category == "i2c":
        return "I2C peripheral interface."
    if category == "jtag":
        return "JTAG debug port."

    return ""


def read_text(path: Path | None) -> str | None:
    if path is None or not path.is_file():
        return None
    return path.read_text()


def find_constraints(source_dir: Path, top: str) -> tuple[str | None, str | None]:
    for ext in (".ldc", ".sdc"):
        path = source_dir / f"{top}{ext}"
        if path.is_file():
            return path.read_text(), ext.lstrip(".")
    return None, None


def humanize_register_name(stem: str) -> str:
    return stem.replace("_", " ").title()


def clean_register_fragment(fragment: str) -> str:
    fragment = re.sub(r"<header[^>]*>.*?</header>", "", fragment, flags=re.DOTALL | re.IGNORECASE)
    fragment = re.sub(r"<footer[^>]*>.*?</footer>", "", fragment, flags=re.DOTALL | re.IGNORECASE)

    def fix_regif_title(match: re.Match[str]) -> str:
        title = html.unescape(re.sub(r"\s+", " ", match.group(1)).strip())
        title = re.sub(r"(?i)register interface\s+register interface", "Register Interface", title)
        title = re.sub(r"(?i)\s+register interface\s*$", "", title).strip()
        title = re.sub(r"(?i)\bregister interface\b", "Register Interface", title, count=1)
        return f'<p class="regif-title">{html.escape(title)}</p>'

    fragment = re.sub(
        r'<p class="regif-title">\s*(.*?)\s*</p>',
        fix_regif_title,
        fragment,
        flags=re.DOTALL | re.IGNORECASE,
    )
    return fragment.strip()


def extract_body_fragment(path: Path) -> str:
    text = path.read_text()
    body = re.search(r"<body[^>]*>(.*)</body>", text, re.DOTALL | re.IGNORECASE)
    fragment = body.group(1) if body else text
    fragment = re.sub(r"<style[^>]*>.*?</style>", "", fragment, flags=re.DOTALL | re.IGNORECASE)
    fragment = re.sub(r"<script[^>]*>.*?</script>", "", fragment, flags=re.DOTALL | re.IGNORECASE)
    fragment = re.sub(
        r'<div[^>]*>\s*<p class="info">Powered by.*?</div>',
        "",
        fragment,
        flags=re.DOTALL | re.IGNORECASE,
    )
    fragment = re.sub(r"Powered by\s*<a[^>]*>\s*SpinalHDL\s*</a>", "", fragment, flags=re.IGNORECASE)
    return clean_register_fragment(fragment)


def parse_ipx(path: Path | None) -> dict[str, str]:
    if path is None or not path.is_file():
        return {}
    root = ET.parse(path).getroot()
    attrs = root.attrib
    files = [node.attrib.get("name", "") for node in root.findall(".//File")]
    return {
        "module": attrs.get("module", ""),
        "source_revision": attrs.get("version", ""),
        "date": attrs.get("date", ""),
        "generator": attrs.get("generator", ""),
        "files": ", ".join(name for name in files if name),
    }


def discover_register_docs(source_dir: Path, top: str) -> list[Path]:
    return sorted(
        path
        for path in source_dir.glob("*.html")
        if path.name != f"{top}.html" and path.stem not in EXCLUDED_REGISTER_STEMS
    )


def discover_header_files(source_dir: Path) -> list[Path]:
    seen: set[str] = set()
    headers: list[Path] = []
    for path in sorted(source_dir.glob("*_def.h")):
        if path.name in seen or path.name in EXCLUDED_HEADER_NAMES:
            continue
        seen.add(path.name)
        headers.append(path)
    return headers


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def port_description_html(port: PortInfo) -> str:
    if port.category == "interrupts" and port.name.endswith("_irq") and port.width:
        name = html.escape(port.name)
        width = html.escape(port.width)
        return (
            f"Interrupt vector <code>{name}</code> {width}; "
            f"bit <em>i</em> maps to CPU interrupt index "
            f"<em>base</em> + <em>i</em> (see device tree overlay)"
        )
    if not port.description:
        return ""
    return html.escape(port.description)


def render_port_sections(ports: list[PortInfo]) -> str:
    if not ports:
        return "<p>No port list available.</p>"

    port_names = {port.name for port in ports}
    by_category: dict[str, list[PortInfo]] = defaultdict(list)
    for port in ports:
        by_category[port.category].append(port)

    sections: list[str] = []
    for category in sorted(by_category, key=category_sort_key):
        group = by_category[category]
        title = category_title(category)
        intro = section_intro(category, group, port_names)
        intro_html = f'<p class="lead">{html.escape(intro)}</p>' if intro else ""

        show_description = any(port_description_html(port) for port in group)
        desc_header = "<th>Description</th>" if show_description else ""
        rows: list[str] = []
        for port in group:
            row = (
                "<tr>"
                f"<td><code>{html.escape(port.name)}</code></td>"
                f"<td>{html.escape(port.direction)}</td>"
                f"<td>{html.escape(port.width) if port.width else '1'}</td>"
            )
            if show_description:
                row += f"<td>{port_description_html(port)}</td>"
            rows.append(row + "</tr>")
        anchor = slugify(title)
        sections.append(
            f'<h3 id="{anchor}">{html.escape(title)}</h3>'
            f"{intro_html}"
            '<table class="data">'
            f"<thead><tr><th>Port</th><th>Direction</th><th>Width</th>{desc_header}</tr></thead>"
            f"<tbody>{''.join(rows)}</tbody></table>"
        )
    return "".join(sections)


def render_artifact(title: str, content: str | None, anchor: str) -> str:
    if not content:
        return ""
    return (
        f'<details class="artifact" id="{anchor}">'
        f"<summary>{html.escape(title)}</summary>"
        f'<div class="content"><pre>{html.escape(content.rstrip())}</pre></div>'
        "</details>"
    )


def render_register_section(path: Path) -> str:
    title = humanize_register_name(path.stem)
    anchor = slugify(path.stem)
    body = extract_body_fragment(path)
    return (
        f'<section id="{anchor}">'
        f"<h2>{html.escape(title)}</h2>"
        f'<div class="regif-embed">{body}</div>'
        "</section>"
    )


def render_header_section(headers: list[Path]) -> str:
    if not headers:
        return ""
    blocks = [
        render_artifact(path.name, path.read_text().rstrip(), slugify(path.name))
        for path in headers
    ]
    return (
        '<section id="software-headers">'
        "<h2>Software Headers</h2>"
        '<p class="lead">C header definitions for register access.</p>'
        f"{''.join(blocks)}"
        "</section>"
    )


def build_html(
    *,
    top: str,
    display_name: str,
    version: str,
    ports: list[PortInfo],
    overlay: str | None,
    constraints: str | None,
    constraints_ext: str | None,
    ipx_info: dict[str, str],
    register_docs: list[Path],
    headers: list[Path],
    css: str,
    main_docs_url: str,
    main_docs_host: str,
) -> str:
    toc_items: list[tuple[str, str]] = [
        ("overview", "Overview"),
        ("ports", "Top-Level Ports"),
    ]
    if overlay:
        toc_items.append(("device-tree", "Device Tree Overlay"))
    if constraints:
        toc_items.append(("constraints", "Timing Constraints"))
    for doc in register_docs:
        toc_items.append((slugify(doc.stem), humanize_register_name(doc.stem)))
    if headers:
        toc_items.append(("software-headers", "Software Headers"))
    if ipx_info or version:
        toc_items.append(("ip-package", "IP Package Manifest"))

    toc = "".join(f'<li><a href="#{anchor}">{html.escape(label)}</a></li>' for anchor, label in toc_items)

    ipx_rows = ""
    if version:
        ipx_rows += (
            "<tr>"
            f"<th>{html.escape('IP Version')}</th>"
            f"<td>{html.escape(version)}</td>"
            "</tr>"
        )
    for key, label in (
        ("module", "Module"),
        ("source_revision", "RTL source revision"),
        ("date", "RTL generated"),
        ("generator", "Generator"),
        ("files", "Packaged Files"),
    ):
        value = ipx_info.get(key, "")
        if not value:
            continue
        if key == "source_revision" and value == version:
            continue
        ipx_rows += (
            "<tr>"
            f"<th>{html.escape(label)}</th>"
            f"<td>{html.escape(value)}</td>"
            "</tr>"
        )

    register_sections = "".join(render_register_section(path) for path in register_docs)
    generated_on = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    constraints_section = ""
    if constraints:
        ext = constraints_ext or "ldc"
        constraints_section = (
            '<section id="constraints">'
            "<h2>Timing Constraints</h2>"
            '<p class="lead">'
            f"Design constraints (<code>{html.escape(top)}.{html.escape(ext)}</code>) shipped with the IP package."
            "</p>"
            + render_artifact(f"{top}.{ext}", constraints, "constraints-source")
            + "</section>"
        )

    device_tree_section = ""
    if overlay:
        device_tree_section = (
            '<section id="device-tree">'
            "<h2>Device Tree Overlay</h2>"
            '<p class="lead">'
            f"Devicetree source (<code>{html.escape(top)}.overlay</code>) for firmware integration."
            "</p>"
            + render_artifact(f"{top}.overlay", overlay, "dts-source")
            + "</section>"
        )

    ip_package_section = ""
    if ipx_info or version:
        ip_package_section = (
            '<section id="ip-package">'
            "<h2>IP Package Manifest</h2>"
            '<p class="lead">Metadata from the IP package manifest.</p>'
            f'<table class="data">{ipx_rows}</table>'
            "</section>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(display_name)} — tinyVision.ai IP Documentation</title>
  <style>
{css}
  </style>
</head>
<body>
  <div class="page">
    <header class="banner">
      <div class="vendor">tinyVision.ai</div>
      <h1>{html.escape(display_name)}</h1>
      <div class="meta">
        <span class="tag">v{html.escape(version)}</span>
        <span class="tag">{html.escape(top)}</span>
      </div>
    </header>

    <div class="docs-callout" role="note">
      <div class="docs-callout-label">Main documentation</div>
      <a class="docs-callout-link" href="{html.escape(main_docs_url)}" target="_blank" rel="noopener noreferrer">
        {html.escape(main_docs_host)}
      </a>
      <p class="docs-callout-text">
        Platform guides, firmware integration, board reference, and the full documentation set.
      </p>
    </div>

    <nav class="toc">
      <h2>Contents</h2>
      <ul>{toc}</ul>
    </nav>

    <section id="overview">
      <h2>Overview</h2>
      <p class="lead">
        This document accompanies the <strong>{html.escape(display_name)}</strong> IP core
        (<code>{html.escape(top)}</code>). It summarizes the top-level interface and packaged artifacts.
        For the broader platform documentation, see
        <a href="{html.escape(main_docs_url)}" target="_blank" rel="noopener noreferrer">{html.escape(main_docs_host)}</a>.
      </p>
      <p>Documentation generated on {html.escape(generated_on)}.</p>
    </section>

    <section id="ports">
      <h2>Top-Level Ports</h2>
      <p class="lead">Ports on the packaged top-level module, grouped by inferred function.</p>
      {render_port_sections(ports)}
    </section>

    {device_tree_section}

    {constraints_section}

    {register_sections}

    {render_header_section(headers)}

    {ip_package_section}

    <footer class="page-footer">
      &copy; tinyVision.ai — IP documentation
    </footer>
  </div>
</body>
</html>
"""


def resolve_ports_file(source_dir: Path, top: str, explicit: Path | None) -> Path | None:
    if explicit is not None and explicit.is_file():
        return explicit
    for candidate in (
        source_dir / f"{top}_top.sv",
        source_dir / f"{top}_top.v",
        source_dir / f"{top}.sv",
        source_dir / f"{top}.v",
    ):
        if candidate.is_file():
            return candidate
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", required=True, help="IP top module name")
    parser.add_argument("--source-dir", required=True, type=Path, help="Directory with IPGen artifacts")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--display-name", default=None)
    parser.add_argument("--version", default="1.0.0")
    parser.add_argument("--ports", type=Path, default=None, help="Top-level SV/V for port extraction")
    parser.add_argument(
        "--main-docs-url",
        default=DEFAULT_MAIN_DOCS_URL,
        help="URL for main platform documentation",
    )
    parser.add_argument(
        "--main-docs-host",
        default=None,
        help="Display label for main docs link (default: host from --main-docs-url)",
    )
    parser.add_argument(
        "--css",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "docs" / "tinyvision_ip.css",
    )
    args = parser.parse_args()

    display_name = args.display_name or args.top
    main_docs_host = args.main_docs_host or urlparse(args.main_docs_url).netloc or "documentation"

    ports_file = resolve_ports_file(args.source_dir, args.top, args.ports)
    raw_ports: list[tuple[str, str, str]] = []
    if ports_file is not None:
        raw_ports = extract_module_ports(ports_file.read_text())
    ports = enrich_ports(raw_ports)

    css = args.css.read_text() if args.css.is_file() else ""
    overlay = read_text(args.source_dir / f"{args.top}.overlay")
    constraints, constraints_ext = find_constraints(args.source_dir, args.top)
    ipx_info = parse_ipx(args.source_dir / f"{args.top}.ipx")
    if args.version:
        ipx_info["source_revision"] = args.version
    register_docs = discover_register_docs(args.source_dir, args.top)
    headers = discover_header_files(args.source_dir)

    doc = build_html(
        top=args.top,
        display_name=display_name,
        version=args.version,
        ports=ports,
        overlay=overlay,
        constraints=constraints,
        constraints_ext=constraints_ext,
        ipx_info=ipx_info,
        register_docs=register_docs,
        headers=headers,
        css=css,
        main_docs_url=args.main_docs_url,
        main_docs_host=main_docs_host,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(doc)
    print(f"Wrote {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
